### ISSUE TITLE
无法更新订单状态

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy_ctptest#1]
下单之后图形界面显示“提交中”，如下图所示：
![20853e25445080694b3f95652f5c7bc](https://user-images.githubusercontent.com/63988546/116357155-c1e67500-a82e-11eb-9e97-3b531ba736e0.png)

底层报错如下图所示：
![2d6e4c498385734a9116f90b06467c8](https://user-images.githubusercontent.com/63988546/116357162-c448cf00-a82e-11eb-8f25-6ba9bd26e7ed.png)

**Comment by vnpy** [comment]
已修复
