### ISSUE TITLE
请增加macOS支持

### ISSUE THREAD

**Issue by VictorCUHKSZ** [vnpy/vnpy_ctptest#12]
我在macOS12.5.1, Mi Max的MacBookPro上安装vnpy_ctptest, 发现没有正常编译出vnctpmd, vnctptd文件，对比vnpy_ctp发现include里面少了mac folder, libs里面少了.a文件，麻烦把这个包支持一下macOS, 谢谢！

**Comment by vnpy** [comment]
vnpy_ctp已经提供了Mac支持，vnpy_ctptest仅用于穿透式测试，这里不计划提供官方的Mac版本支持了

**Comment by hzbnb** [comment]
现在支持mac了吗
