### ISSUE TITLE
Simnow现在无法连接，报错提示4040

### ISSUE THREAD

**Issue by nov12** [vnpy/vnpy_ctptest#2]
系统Windows10
我上上个星期好像还能连，不知道是不是simnow更新api了。
我用simnow提供的上期端的dll直接替换后Python提示无法导入，看来是不是要重新编译。

`Decrypt handshake data failed

Decrypt handshake data failed

2021-06-11 12:21:10,281  INFO: 行情接口报错，代码：4040，信息：CTP:API Front shake hand err: decode err
CThostFtdcUserApiImplBase::OnSessionDisconnected[0000016D5D283458][-457900031][ 4097]

2021-06-11 12:21:11,969  INFO: 交易服务器连接断开，原因4097
Decrypt handshake data failed`

**Comment by vnpy** [comment]
simnow请使用CTP接口，而不是CTPTEST
