### ISSUE TITLE
请增加广州期货交易所的支持

### ISSUE THREAD

**Issue by rwayan** [vnpy/vnpy_ctptest#9]
否则会报KeyError
At:
  d:\ProgramData\Anaconda3\lib\site-packages\vnpy_ctptest\gateway\ctptest_gateway.py(597): onRspQryInstrument

KeyError: ('GFEX',)

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_ctptest/commit/04bbdfcc5e587ff44da8dae799e83011c330d40d
